baseURL = "https://mokagio.github.io/thinkingoutloud/"
locale = "en-us"
title = "Thinking Out Loud"
theme = "simple-hugo-theme"

[pagination]
pagerSize = 20
path = "page"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.typographer]
disable = false

[permalinks]
posts = "/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
url = "/posts/index.xml"
name = "rss"
weight = 1
